import type { LaporanIKU } from '../types';

const baseTW = {
  realisasiTW3: null,
  persentaseTW3: 0,
  ketTW3: '',
  realisasiTW4: null,
  persentaseTW4: 0,
  ketTW4: '',
  realisasiAnggaranTW3: 0,
  persentaseAnggaranTW3: 0,
  realisasiAnggaranTW4: 0,
  persentaseAnggaranTW4: 0,
};

export const sampleLaporanIKU: LaporanIKU[] = [
  {
    id: 1,
    no: 1,
    sasaranStrategis: 'Meningkatnya kinerja, kompetensi dan disiplin ASN',
    indikator: 'Persentase capaian kinerja, kompetensi, dan disiplin ASN',
    caraPengukuran: 'Persentase kinerja ditambah persentase kompetensi ditambah persentase disiplin dibagi 3',
    targetTahun: 16.46,
    realisasiTW1: null,
    persentaseTW1: 0,
    ketTW1: 'Kinerja: Perhitungan dilakukan pada akhir tahun. Kompetensi: Belum dilakukan pemetaan kompetensi di Triwulan I 2026 karena tidak ada anggaran. Disiplin: di Triwulan I tidak ada ASN yang melanggar disiplin',
    realisasiTW2: 0.59,
    persentaseTW2: 3.57,
    ketTW2: 'Kinerja: Perhitungan dilakukan pada akhir tahun. Kompetensi: Pada Triwulan II, ada 126 pegawai yang terdiri dari jabatan fungsional guru, kesehatan, dan teknis yang mengikuti Uji Kompetensi. Disiplin: Pada Triwulan II ada 1 orang yang melanggar disiplin, hukdis tingkat berat (Pemberhentian dengan hormat tidak atas permintaan sendiri sebagai PNS)',
    program: 'Program Kepegawaian Daerah',
    pagu: 364134300,
    realisasiAnggaranTW1: 17244445,
    persentaseAnggaranTW1: 4.74,
    realisasiAnggaranTW2: 210426590,
    persentaseAnggaranTW2: 57.79,
    tahun: 2026,
    ...baseTW,
  },
  {
    id: 2,
    no: 2,
    sasaranStrategis: 'Meningkatnya Kualitas Tata Kelola dan Dukungan Administratif Dalam Penyelenggaraan Pemerintahan Daerah',
    indikator: 'Nilai SAKIP Perangkat Daerah',
    caraPengukuran: 'Nilai LHE AKIP yang dikeluarkan Inspektorat Daerah',
    targetTahun: 80.02,
    realisasiTW1: null,
    persentaseTW1: 0,
    ketTW1: 'Belum dilakukan evaluasi AKIP',
    realisasiTW2: null,
    persentaseTW2: 0,
    ketTW2: 'Proses evaluasi AKIP masih berjalan',
    program: 'Program Penunjang Urusan Pemerintahan Daerah Kabupaten/Kota',
    pagu: 7263549243,
    realisasiAnggaranTW1: 1849143365,
    persentaseAnggaranTW1: 25.46,
    realisasiAnggaranTW2: 3486879210,
    persentaseAnggaranTW2: 48.01,
    tahun: 2026,
    ...baseTW,
  },
  {
    id: 3,
    no: 3,
    sasaranStrategis: 'Meningkatnya Kualifikasi dan Kompetensi ASN',
    indikator: 'Indeks Profesionalisme ASN Dimensi Kompetensi',
    caraPengukuran: 'Persentase ASN yang melanjutkan jenjang pendidikan formal ditambah Persentase ASN yang telah mengikuti pelatihan dibagi 2',
    targetTahun: 10.83,
    realisasiTW1: 6.12,
    persentaseTW1: 56.53,
    ketTW1: 'Pendidikan: Jumlah Pegawai dengan Pendidikan S2/S3 sebanyak 524 orang dibagi jumlah pegawai dengan Pendidikan S1 sebanyak 4.395 orang. Pelatihan: Nilai rata-rata pelatihan (Kepemimpinan = 0/195, Teknis = 63/7.221, dan Fungsional = 3/3.212)',
    realisasiTW2: 6.2,
    persentaseTW2: 57.28,
    ketTW2: 'Pendidikan: Jumlah Pegawai dengan Pendidikan S2/S3 sebanyak 527 orang dibagi jumlah pegawai dengan Pendidikan S1 sebanyak 4.395 orang. Pelatihan: Nilai rata-rata pelatihan (Kepemimpinan = 0/195, Teknis = 74/7.195, dan Fungsional = 7/3.212)',
    program: 'Program Pengembangan Sumber Daya Manusia',
    pagu: 18499835,
    realisasiAnggaranTW1: 0,
    persentaseAnggaranTW1: 0,
    realisasiAnggaranTW2: 0,
    persentaseAnggaranTW2: 0,
    tahun: 2026,
    ...baseTW,
  },
];
