import type { IKUData } from '../types';

export const sampleData: IKUData[] = [
  { id: 1, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Administrasi Kepegawaian Perangkat Daerah', subKegiatan: 'Sub Kegiatan Penyusunan Rencana Kebutuhan', indikator: 'Persentase Perencanaan Kebutuhan ASN yang sesuai dengan Standar Kompetensi', satuan: '%', targetRenstra: 83, targetTahun: 83, realisasiTW1: null, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 2, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Administrasi Kepegawaian Perangkat Daerah', subKegiatan: 'Sub Kegiatan Pengelolaan Data Kepegawaian', indikator: 'Persentase Pengisian Jabatan Pimpinan Tinggi yang terisi sesuai kompetensi', satuan: '%', targetRenstra: 100, targetTahun: 100, realisasiTW1: 30, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 30, persentase: 30, targetAnggaran: 1737520, realisasiAnggaran: 981260, persentaseAnggaran: 56.48, tahun: 2026 },
  { id: 3, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Pengadaan, Pemberhentian dan Informasi Kepegawaian', subKegiatan: 'Sub Kegiatan Koordinasi dan Fasilitasi Pengadaan PNS', indikator: 'Persentase Pemenuhan Kebutuhan ASN', satuan: '%', targetRenstra: 100, targetTahun: 100, realisasiTW1: 78, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 78, persentase: 78, targetAnggaran: 12173780, realisasiAnggaran: 5030380, persentaseAnggaran: 41.32, tahun: 2026 },
  { id: 4, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Pengadaan, Pemberhentian dan Informasi Kepegawaian', subKegiatan: 'Sub Kegiatan Pengelolaan Sistem Informasi Kepegawaian', indikator: 'Penerapan Sistem Informasi Kepegawaian', satuan: 'Nilai', targetRenstra: 90, targetTahun: 90, realisasiTW1: 100, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 100, persentase: 100, targetAnggaran: 23000000, realisasiAnggaran: 1514790, persentaseAnggaran: 6.59, tahun: 2026 },
  { id: 5, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Pengadaan, Pemberhentian dan Informasi Kepegawaian', subKegiatan: 'Sub kegiatan Fasilitasi Lembaga Profesi ASN', indikator: 'Layanan Kepegawaian', satuan: 'Nilai', targetRenstra: 80, targetTahun: 80, realisasiTW1: 100, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 100, persentase: 100, targetAnggaran: 3400000, realisasiAnggaran: 543800, persentaseAnggaran: 16, tahun: 2026 },
  { id: 6, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Pengadaan, Pemberhentian dan Informasi Kepegawaian', subKegiatan: 'Sub Kegiatan Koordinasi Pelaksanaan Administrasi PNS', indikator: 'Indeks Kematangan Organisasi', satuan: 'POIN', targetRenstra: 48, targetTahun: 47.25, realisasiTW1: 0, realisasiTW2: 0, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 7263549243, realisasiAnggaran: 3486879210, persentaseAnggaran: 48.01, tahun: 2026 },
  { id: 7, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Pengembangan Kompetensi ASN', subKegiatan: 'Sub Kegiatan Peningkatan Kapasitas Kinerja ASN', indikator: 'Pengembangan Kompetensi ASN', satuan: '%', targetRenstra: 91, targetTahun: 91, realisasiTW1: 70, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 70, persentase: 76.92, targetAnggaran: 69000000, realisasiAnggaran: 22980000, persentaseAnggaran: 33.3, tahun: 2026 },
  { id: 8, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Penilaian dan Evaluasi Kinerja Aparatur', subKegiatan: 'Sub Kegiatan Pembinaan Disiplin ASN', indikator: 'Pembinaan Disiplin ASN', satuan: 'Orang', targetRenstra: 25, targetTahun: 25, realisasiTW1: 15, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 15, persentase: 60, targetAnggaran: 4264155, realisasiAnggaran: 2862790, persentaseAnggaran: 67.14, tahun: 2026 },
  { id: 9, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Penilaian dan Evaluasi Kinerja Aparatur', subKegiatan: 'Sub Kegiatan Penyusunan Kebijakan Penilaian Kinerja', indikator: 'Penilaian Kinerja ASN', satuan: '%', targetRenstra: 92, targetTahun: 92, realisasiTW1: null, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 10, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Penilaian dan Evaluasi Kinerja Aparatur', subKegiatan: 'Sub Kegiatan Pengelolaan Pemberian Penghargaan', indikator: 'Penghargaan ASN', satuan: 'Orang', targetRenstra: 0, targetTahun: 0, realisasiTW1: 0, realisasiTW2: 0, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 11, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Penilaian dan Evaluasi Kinerja Aparatur', subKegiatan: 'Sub Kegiatan Pengelolaan Tanda Jasa', indikator: 'Pengelolaan Talenta ASN', satuan: 'Orang', targetRenstra: 151, targetTahun: 151, realisasiTW1: null, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 12, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Mutasi dan Promosi ASN', subKegiatan: 'Sub Kegiatan Pengelolaan Mutasi ASN', indikator: 'Mutasi dan Promosi ASN', satuan: 'Dokumen', targetRenstra: 1, targetTahun: 1, realisasiTW1: null, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 13, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Mutasi dan Promosi ASN', subKegiatan: 'Sub Kegiatan Pengelolaan Kenaikan Pangkat ASN', indikator: 'Perencanaan Kebutuhan ASN', satuan: 'Dokumen', targetRenstra: 1, targetTahun: 1, realisasiTW1: null, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 14, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Mutasi dan Promosi ASN', subKegiatan: 'Sub Kegiatan Pengelolaan Promosi ASN', indikator: 'Persentase Pegawai dengan SKP Bernilai Baik', satuan: '%', targetRenstra: 92, targetTahun: 92, realisasiTW1: null, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 15, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Pengembangan Kompetensi ASN', subKegiatan: 'Sub Kegiatan Fasilitasi Pengembangan Karir', indikator: 'Persentase ASN yang Ditingkatkan Kompetensinya sesuai dengan Kebutuhan', satuan: '%', targetRenstra: 14.1, targetTahun: 14.1, realisasiTW1: 0.01, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0.01, persentase: 0.01, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 16, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Perencanaan, Penganggaran, dan Evaluasi Kinerja', subKegiatan: 'Sub Kegiatan Penyusunan Dokumen Perencanaan', indikator: 'Jumlah Dokumen Perencanaan Perangkat Daerah', satuan: 'Dokumen', targetRenstra: 4, targetTahun: 5, realisasiTW1: 1, realisasiTW2: 2, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 3, persentase: 60, targetAnggaran: 23000000, realisasiAnggaran: 1514790, persentaseAnggaran: 6.59, tahun: 2026 },
  { id: 17, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Perencanaan, Penganggaran, dan Evaluasi Kinerja', subKegiatan: 'Sub Kegiatan Evaluasi Kinerja Perangkat Daerah', indikator: 'Jumlah Laporan Evaluasi Kinerja Perangkat Daerah', satuan: 'Laporan', targetRenstra: 4, targetTahun: 4, realisasiTW1: 1, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 1, persentase: 25, targetAnggaran: 4264155, realisasiAnggaran: 2862790, persentaseAnggaran: 67.14, tahun: 2026 },
  { id: 18, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Administrasi Keuangan Perangkat Daerah', subKegiatan: 'Sub Kegiatan Penyediaan Gaji dan Tunjangan ASN', indikator: 'Jumlah Orang yang Menerima Gaji dan Tunjangan ASN', satuan: 'Orang', targetRenstra: 50, targetTahun: 50, realisasiTW1: 50, realisasiTW2: 50, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 50, persentase: 100, targetAnggaran: 6323717358, realisasiAnggaran: 3149951078, persentaseAnggaran: 49.8, tahun: 2026 },
  { id: 19, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Administrasi Keuangan Perangkat Daerah', subKegiatan: 'Sub Kegiatan Laporan Keuangan Akhir Tahun', indikator: 'Jumlah Laporan Keuangan Akhir Tahun SKPD', satuan: 'Laporan', targetRenstra: 1, targetTahun: 1, realisasiTW1: null, realisasiTW2: 1, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 1, persentase: 100, targetAnggaran: 1737520, realisasiAnggaran: 981260, persentaseAnggaran: 56.48, tahun: 2026 },
  { id: 20, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Administrasi Umum Perangkat Daerah', subKegiatan: 'Sub Kegiatan Fasilitasi Kunjungan Tamu', indikator: 'Jumlah Laporan Fasilitasi Kunjungan Tamu', satuan: 'Laporan', targetRenstra: 10, targetTahun: 10, realisasiTW1: 3, realisasiTW2: 3, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 3, persentase: 30, targetAnggaran: 7500000, realisasiAnggaran: 6309900, persentaseAnggaran: 84.13, tahun: 2026 },
  { id: 21, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Administrasi Umum Perangkat Daerah', subKegiatan: 'Sub Kegiatan Penyelenggaraan Rapat Koordinasi', indikator: 'Jumlah Laporan Penyelenggaraan Rapat Koordinasi', satuan: 'Laporan', targetRenstra: 18, targetTahun: 18, realisasiTW1: 4, realisasiTW2: 4, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 4, persentase: 22.22, targetAnggaran: 147057000, realisasiAnggaran: 42390463, persentaseAnggaran: 28.83, tahun: 2026 },
  { id: 22, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Penyediaan Jasa Penunjang', subKegiatan: 'Sub Kegiatan Penyediaan Jasa Komunikasi', indikator: 'Jumlah Laporan Penyediaan Jasa Komunikasi', satuan: 'Laporan', targetRenstra: 12, targetTahun: 12, realisasiTW1: 6, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 6, persentase: 50, targetAnggaran: 124100000, realisasiAnggaran: 52687745, persentaseAnggaran: 42.46, tahun: 2026 },
  { id: 23, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Pemeliharaan Barang Milik Daerah', subKegiatan: 'Sub Kegiatan Pemeliharaan Peralatan dan Mesin', indikator: 'Jumlah Peralatan dan Mesin yang Dipelihara', satuan: 'Unit', targetRenstra: 3, targetTahun: 3, realisasiTW1: 1, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 1, persentase: 33.33, targetAnggaran: 219506910, realisasiAnggaran: 80124613, persentaseAnggaran: 36.5, tahun: 2026 },
  { id: 24, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Pengadaan Barang Milik Daerah', subKegiatan: 'Sub Kegiatan Pengadaan Sarana dan Prasarana', indikator: 'Jumlah Unit Sarana dan Prasarana Pendukung', satuan: 'Unit', targetRenstra: 1, targetTahun: 1, realisasiTW1: null, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 25, program: 'PROGRAM PENGEMBANGAN SUMBER DAYA MANUSIA', kegiatan: 'Kegiatan Pengembangan Kompetensi Teknis', subKegiatan: 'Sub Kegiatan Penyelenggaraan Pengembangan Kompetensi', indikator: 'Persentase ASN yang Mendapatkan Pengembangan Kompetensi Teknis', satuan: '%', targetRenstra: 14.1, targetTahun: 14.1, realisasiTW1: 0.01, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0.01, persentase: 0.01, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 26, program: 'PROGRAM PENGEMBANGAN SUMBER DAYA MANUSIA', kegiatan: 'Kegiatan Sertifikasi, Kelembagaan, Pengembangan Kompetensi', subKegiatan: 'Sub Kegiatan Penyelenggaraan Pengembangan Kompetensi Manajerial', indikator: 'Persentase Realisasi Pendidikan dan Pelatihan', satuan: '%', targetRenstra: 100, targetTahun: 100, realisasiTW1: 50, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 50, persentase: 50, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 27, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Perencanaan, Penganggaran, dan Evaluasi Kinerja', subKegiatan: 'Sub Kegiatan Koordinasi Dokumen RKA-SKPD', indikator: 'Jumlah Dokumen RKA-SKPD', satuan: 'Dokumen', targetRenstra: 1, targetTahun: 1, realisasiTW1: null, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 0, persentase: 0, targetAnggaran: 3400000, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
  { id: 28, program: 'PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH', kegiatan: 'Kegiatan Administrasi Kepegawaian Perangkat Daerah', subKegiatan: 'Sub Kegiatan Pengelolaan Laporan Capaian Kinerja', indikator: 'Jumlah Laporan Capaian Kinerja dan Ikhtisar Realisasi', satuan: 'Laporan', targetRenstra: 8, targetTahun: 8, realisasiTW1: 2, realisasiTW2: 2, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 4, persentase: 50, targetAnggaran: 2611200, realisasiAnggaran: 652800, persentaseAnggaran: 25, tahun: 2026 },
  { id: 29, program: 'PROGRAM KEPEGAWAIAN DAERAH', kegiatan: 'Kegiatan Pengembangan Kompetensi ASN', subKegiatan: 'Sub Kegiatan Fasilitasi Pengembangan Karir dalam Jabatan Fungsional', indikator: 'Jumlah ASN Jabatan Fungsional yang Mendapatkan Layanan Pengembangan Karir', satuan: 'Orang', targetRenstra: 70, targetTahun: 70, realisasiTW1: 239, realisasiTW2: null, realisasiTW3: null, realisasiTW4: null, realisasiTahun: 239, persentase: 341.43, targetAnggaran: 0, realisasiAnggaran: 0, persentaseAnggaran: 0, tahun: 2026 },
];

export const triwulanOptions = ['Semua Triwulan', 'Triwulan I', 'Triwulan II', 'Triwulan III', 'Triwulan IV'];
export const tahunOptions = [2025, 2026, 2027];
